@extends('layouts.app')
 
@section('content')

<div class="card">
    <div class="card-body">
        <p style="text-align: center;"><strong><span style="font-size: 20px; color: rgb(255, 255, 255);">I. PREAMBUŁA</span></strong></p>
        <p><span style="color: rgb(255, 255, 255);">1. Niniejszy dokument określa warunki dostępu i korzystania ze strony internetowej, zwany będzie dalej: &bdquo;Og&oacute;lne warunki&rdquo;.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Każdy Użytkownik z chwilą podjęcia czynności zmierzających do korzystania ze strony internetowej zobowiązany jest do zapoznania się, przestrzegania oraz akceptacji Og&oacute;lnych warunk&oacute;w, bez ograniczeń i zastrzeżeń.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. W przypadku niewyrażenia zgody na wszystkie Og&oacute;lne warunki należy zaprzestać korzystania ze strony internetowej i natychmiast ją opuścić.</span></p>
        <p><span style="color: rgb(255, 255, 255);">4. Wszystkie nazwy handlowe, nazwy firm i ich logo, użyte na stronie internetowej należą do ich właścicieli i są używane wyłącznie w celach identyfikacyjnych. Mogą być one zastrzeżone znakami towarowymi.</span></p>
        <p><span style="color: rgb(255, 255, 255);">5. Zabrania się nieuprawnionego korzystania z zawartości strony internetowej, utwor&oacute;w lub informacji, jak też ich nieuprawnionej reprodukcji, retransmisji lub innego użycia jakiegokolwiek elementu strony internetowej, gdyż takie działanie może naruszać m.in. prawa autorskie lub chronione znaki towarowe.</span></p>
        <p><span style="color: rgb(255, 255, 255);">6. Pytania lub uwagi dotyczące strony internetowej można zgłaszać pisząc na adres email: <a data-fr-linked="true" href="mailto:administrator@ilezaauto.pl">administrator@ilezaauto.pl</a></span></p>
        <p style="text-align: center;"><span style="font-size: 20px; color: rgb(255, 255, 255);"><strong>II. DEFINICJE</strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">2. <strong>PRAWO WŁAŚCIWE&nbsp;</strong>&ndash; Do cel&oacute;w realizacji Og&oacute;lnych warunk&oacute;w zastosowanie ma prawo polskie;</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. <strong>STRONA INTERNETOWA&nbsp;</strong>&ndash; narzędzie, o nazwie: <a href="https://ilezaauto.pl">https://ilezaauto.pl</a>&nbsp; służące do świadczenia usług elektronicznych;</span></p>
        <p><span style="color: rgb(255, 255, 255);">4. <strong>UŻYTKOWNIK</strong> &ndash; osoba fizyczna, osoba prawna albo jednostka organizacyjna nieposiadająca osobowości prawnej, kt&oacute;rej ustawa przyznaje zdolność prawną, korzystająca z usług elektronicznych dostępnych w ramach strony internetowej;</span></p>
        <p><span style="color: rgb(255, 255, 255);">5. <strong>W</strong></span><span style='color: rgb(255, 255, 255); font-family: "Times New Roman"; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;'><strong>ARUNK</strong></span><span style="color: rgb(255, 255, 255);"><strong>I</strong> &ndash; zbi&oacute;r wszystkich postanowień m.in. niniejszych Og&oacute;lnych warunk&oacute;w, zasad polityki prywatności, plik&oacute;w cookies, regulaminu korzystania ze sklepu internetowego oraz wszelkich innych warunk&oacute;w, znajdujących się na stronie internetowej, kt&oacute;re dotyczą określonych funkcji, właściwości lub promocji, jak r&oacute;wnież obsługi klienta;</span></p>
        <p><span style="color: rgb(255, 255, 255);">6. <strong>WŁAŚCICIEL</strong> &ndash; Podmiot udostępniający niniejszą stronę internetową, mianowicie: Rafał Makowski, Dariusz Kaczmarek, Dawid Łukaszyk z siedzibą przy: ul Andersa 7, 64-800 Chodzież.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">III. ZAKRES WARUNK&Oacute;W</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Właściciel zapewnia dostęp do zawartości strony internetowej, zgodnie z poniższymi Og&oacute;lnymi warunkami.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Zawartość i dane publikowane na stronie internetowej mają charakter informacji dla os&oacute;b zainteresowanych i mogą być wykorzystywane jedynie do cel&oacute;w informacyjnych.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. Właściciel ma prawo zamieszczania treści reklamowych, kt&oacute;re stanowią integralną część serwisu i prezentowanych w nim materiał&oacute;w.</span></p>
        <p><span style="color: rgb(255, 255, 255);">4. Użytkownicy mogą korzystać z dostępu i usług oferowanych na stronie internetowej, pod warunkiem uprzedniego wyrażenia zgody na Og&oacute;lne warunki.</span></p>
        <p style="text-align: center;"><span style="font-size: 20px; color: rgb(255, 255, 255);"><strong>IV. ZASADY KORZYSTANIA ZE STRONY INTERNETOWEJ</strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Strona internetowa jest obsługiwana przez wszelkiego rodzaju przeglądarki internetowe. Nie wymaga się żadnych szczeg&oacute;lnych właściwości urządzenia końcowego Użytkownika.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Po zaakceptowaniu Warunk&oacute;w, Użytkownik ma prawo przeglądać, kopiować, drukować oraz rozpowszechniać, bez dokonywania zmian w treści, zawartość niniejszej strony internetowej, pod warunkiem, że:</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">a. treści te będą wykorzystywane wyłącznie informacyjnie, w celach niekomercyjnych;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">b. każda wykonana kopia będzie zawierała informacje na temat praw autorskich lub dane dotyczące autora treści.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. Zakazane jest używanie i kopiowanie oprogramowania, proces&oacute;w i technologii, stanowiących część strony internetowej.</span></p>
        <p><span style="color: rgb(255, 255, 255);">4. Użytkownicy mogą korzystać ze strony internetowej jedynie w poszanowaniu przepis&oacute;w ustawy prawo telekomunikacyjne, ustawy o świadczeniu usług drogą elektroniczną i odpowiednich przepis&oacute;w prawa cywilnego.</span></p>
        <p><span style="color: rgb(255, 255, 255);">5. Zabronione jest korzystanie ze strony internetowej:</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">a. w spos&oacute;b prowadzący do naruszenia obowiązujących przepis&oacute;w prawa;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">b. w jakikolwiek spos&oacute;b niezgodny z prawem lub nieuczciwy, albo w spos&oacute;b, zmierzający do osiągnięcia niezgodnego z prawem lub nieuczciwego celu;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">c. do cel&oacute;w związanych z wyrządzaniem szkody dzieciom lub pr&oacute;b wyrządzenia im jakiejkolwiek szkody;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">d. do wysyłania, świadomego otrzymywania, wgrywania lub używania treści niezgodnych z Og&oacute;lnymi warunkami;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">e. do przekazywania lub prowokowania wysyłki jakichkolwiek niezam&oacute;wionych lub nieuprawnionych reklam lub materiał&oacute;w promocyjnych, jak r&oacute;wnież jakichkolwiek form podobnych, zaliczanych do zbiorczej kategorii SPAM;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">f. do świadomego przekazywania jakichkolwiek danych, wysyłania lub wgrywania jakichkolwiek materiał&oacute;w zawierających wirusy, konie trojańskie, oprogramowanie szpiegujące (spyware), oprogramowanie z reklamami (adware) lub inny szkodliwy program lub zbliżone kody komputerowe zaprogramowane, by niekorzystnie wpływać lub zagrażać na funkcjonowanie jakiegokolwiek oprogramowania lub sprzętu komputerowego albo niekorzystnie wpływać lub zagrażać Użytkownikowi.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">V. COOKIES</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Strona internetowa używa plik&oacute;w cookies (ciasteczka) lub podobną technologię (dalej łącznie nazywane: &bdquo;cookies&rdquo;) do zbierania informacji o dostępie Użytkownika do strony internetowej (np. za pomocą komputera lub smartfona) oraz jego preferencjach. Są one wykorzystywane m.in. w celach reklamowych i statystycznych oraz w celu dostosowania strony internetowej do indywidualnych potrzeb Użytkownika.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Pliki cookies to fragmenty informacji, kt&oacute;re zawierają unikalny kod referencyjny, kt&oacute;ry strona internetowa przesyła na urządzenie Użytkownika, w celu przechowywania, a czasem śledzenia informacji dotyczących używanego urządzenia. Zwykle nie pozwalają one zidentyfikować osoby Użytkownika. Ich gł&oacute;wnym zadaniem jest lepsze dopasowanie strony internetowej do Użytkownika.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. Niekt&oacute;re z plik&oacute;w cookies, występujące na stronie internetowej, są dostępne tylko przez czas trwania danej sesji internetowej i wygasają po zamknięciu przeglądarki. Inne pliki cookies służą do zapamiętywania Użytkownika, kt&oacute;ry po powrocie na stronę internetową, jest na niej rozpoznawany. Są one w&oacute;wczas zachowywane przed dłuższy czas.</span></p>
        <p><span style="color: rgb(255, 255, 255);">4. Wszystkie pliki cookies, występujące na stronie internetowej, są ustalane przez Właściciela.</span></p>
        <p><span style="color: rgb(255, 255, 255);">5. Wszystkie pliki cookies, używane przez niniejszą stronę internetową, są zgodne z obowiązującym prawem Unii Europejskiej.</span></p>
        <p><span style="color: rgb(255, 255, 255);">6. Większość Użytkownik&oacute;w i niekt&oacute;rych przeglądarek mobilnych automatycznie akceptuje pliki cookies. Jeżeli ustawienia te pozostaną bez zmian, pliki cookies zostaną zapisane w pamięci urządzenia.</span></p>
        <p><span style="color: rgb(255, 255, 255);">7. Użytkownik może zmienić preferencje dotyczące akceptacji plik&oacute;w cookies lub zmienić przeglądarkę, aby m&oacute;c otrzymać za każdym razem stosowne powiadomienie, gdy funkcja cookies jest ustawiona. Aby zmienić ustawienia akceptacji cookies, należy dostosować ustawienia w przeglądarce.</span></p>
        <p><span style="color: rgb(255, 255, 255);">8. Warto pamiętać, że blokowanie lub usuwanie plik&oacute;w cookies może uniemożliwić pełne korzystanie ze strony internetowej.</span></p>
        <p><span style="color: rgb(255, 255, 255);">9. Pliki cookies będą wykorzystywane do niezbędnego zarządzania sesją, w tym:</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">a. Tworzenia specjalnej sesji logowania dla Użytkownika strony internetowej, aby strona zapamiętała, że Użytkownik jest zalogowany, a jego żądania były dostarczane w spos&oacute;b skuteczny, bezpieczny i sp&oacute;jny;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">b. Rozpoznawania Użytkownika, kt&oacute;ry już wcześniej odwiedził stronę internetową co pozwala na identyfikację liczby unikalnych użytkownik&oacute;w, kt&oacute;rzy skorzystali z serwisu i pozwala upewnić się co do wystarczającej pojemności serwisu dla liczby nowych użytkownik&oacute;w;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">c. Rozpoznawania, czy osoba odwiedzająca stronę internetową jest zarejestrowana na stronie internetowej;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">d. Rejestrowanie informacji z urządzenia Użytkownika, w tym: pliki cookies, adres IP i informacje o używanej przeglądarce, w celu możliwości diagnozowania problem&oacute;w, administrowania i śledzenia Użytkowania witryny;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">e. Dostosowywania element&oacute;w układu szaty graficznej lub zawartości strony internetowej;</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">f. Zbierania informacji statystycznych o tym, jak Użytkownik korzysta ze strony, w celu możliwości ulepszania witryny i stwierdzenia, kt&oacute;re zakresy strony internetowej są najbardziej popularne dla Użytkownik&oacute;w.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">VI. LINKI ZEWNĘTRZNE</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Odnośniki znajdujące się na niniejszej stronie, do innych stron internetowych, są podane wyłącznie w celu informacyjnym.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Właściciel strony internetowej nie ponosi odpowiedzialności za treści znajdujące się na innych witrynach, ani za jakiekolwiek szkody wynikające z ich użytkowania.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">VII. POSZANOWANIE WŁASNOŚCI INTELEKTUALNEJ</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Strona internetowa oraz jej treści mogą być chronione prawami autorskimi, prawami dotyczącymi znak&oacute;w towarowych oraz innymi przepisami, związanymi z ochroną własności intelektualnej.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Znaki, loga i inne spersonalizowane emblematy Właściciela, pojawiające się na stronie internetowej (zwane łącznie: &bdquo;Znakami&rdquo;), stanowią znaki towarowe Właściciela.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. Z wyjątkiem osobnych, indywidualnych, pisemnych upoważnień, Użytkownik nie może wykorzystywać przez siebie, należących do Właściciela, Znak&oacute;w: osobno, ani w zestawieniu z innymi elementami słownymi lub graficznymi, szczeg&oacute;lnie w informacjach prasowych, reklamach, materiałach promocyjnych, marketingowych, w mediach, w materiałach pisemnych lub ustnych, w formie elektronicznej, w formie wizualnej ani w żadnej innej formie.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">VIII. OCHRONA DANYCH UŻYTKOWNIKA</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">Właściciel szanuje w pełni prywatność Użytkownik&oacute;w. Szczeg&oacute;łowe informacje na temat sposobu gromadzenia i przetwarzania danych osobowych Użytkownika lub innych informacji, jak r&oacute;wnież sytuacji, w kt&oacute;rych Właściciel może je ujawniać, znajdują się w zakładce Polityka Prywatności.</span></p>
        <p><span style="color: rgb(255, 255, 255);">XIII. OGRANICZENIE ODPOWIEDZIALNOŚCI.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Strona internetowa nie zapewnia żadnych gwarancji dotyczących jej treści, w szczeg&oacute;lności gwarancji bezpieczeństwa, bezbłędności, braku wirus&oacute;w czy złośliwych kod&oacute;w, gwarancji dotyczących poprawnego działania czy jakości.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. Strona internetowa nie zapewnia żadnej rękojmi, wyraźnej lub dorozumianej, w tym gwarancji przydatności handlowej lub przydatności do określonego celu, nienaruszenia praw autorskich, dostosowania, bezpieczeństwa i rzetelności informacji.</span></p>
        <p><span style="color: rgb(255, 255, 255);">4. Użytkownik korzysta ze strony internetowej na własne ryzyko i przyjmuje na siebie pełną odpowiedzialność za szkody związane lub wynikające z jej wykorzystania, zar&oacute;wno bezpośrednie jak i pośrednie, uboczne, następcze, moralne, lub inne szkody z tytułu odpowiedzialności umownej, deliktowej, z tytułu zaniedbań, w tym m.in. za utratę danych lub usług.</span></p>
        <p><span style="color: rgb(255, 255, 255);">5. Strona internetowa nie ponosi żadnej odpowiedzialności za linki zamieszczone na stronie internetowej, szczeg&oacute;lnie jeśli prowadzą do witryn, zasob&oacute;w lub narzędzi utrzymywanych przez osoby trzecie.</span></p>
        <p><span style="color: rgb(255, 255, 255);">6. Właściciel nie ponosi odpowiedzialności, jeśli strona internetowa jest z jakichkolwiek przyczyn tymczasowo lub długookresowo niedostępna.</span></p>
        <p><span style="color: rgb(255, 255, 255);">7. Właściciel nie ponosi odpowiedzialności za informacje przekazywane na stronie internetowej, ani też nie może zapewnić całkowitego bezpieczeństwa transakcji lub komunikacji, prowadzonych za pomocą strony internetowej.</span></p>
        <p><span style="color: rgb(255, 255, 255);">8. Pomimo podejmowania przez Właściciela największych starań, w kwestii zapewnienia dokładności i aktualności strony internetowej, mogą pojawić się niezamierzone przez Właściciela błędy, kt&oacute;re Użytkownik, po ich wykryciu, proszony jest zgłaszać Właścicielowi.</span></p>
        <p><span style="color: rgb(255, 255, 255);">9. Wszystkie wskazane powyżej wyłączenia i ograniczenia odpowiedzialności obowiązują w najszerszym dopuszczalnym prawnie zakresie, obejmując każdy typ istniejącej odpowiedzialności m.in. odpowiedzialności kontraktowej, deliktowej i każdej innej przewidzianej w polskim lub zagranicznym porządku prawnym.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">IX. WAŻNOŚĆ POSTANOWIEŃ</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Gdyby kt&oacute;rekolwiek z postanowień Og&oacute;lnych warunk&oacute;w było lub miało stać się nieważne lub bezskuteczne, w dowolnym systemie prawnym, pozostała część Warunk&oacute;w pozostaje ważna i nienaruszona. Strony zastąpią nieważne lub bezskuteczne postanowienie innym, kt&oacute;re możliwie najwierniej oddaje zamierzony cel. Odpowiednio dotyczy to także ewentualnych luk w Og&oacute;lnych warunkach.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Gdyby kt&oacute;rekolwiek z postanowień Og&oacute;lnych warunk&oacute;w było lub miało stać się nieważne lub bezskuteczne, w jednym lub kilku systemach prawnych, wszystkie postanowienia Og&oacute;lnych warunk&oacute;w zachowują ważność w każdym innym systemie prawnym.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style='font-family: "Times New Roman", Times, serif; font-size: 20px;'>X. STOSUNEK DO ZAWARTYCH UM&Oacute;W</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">Jeśli nie postanowiono inaczej, Og&oacute;lne warunki stanowią kompletną i wyczerpującą umowę pomiędzy Użytkownikiem i Właścicielem, dotyczącą korzystania ze strony internetowej, w zakresie treści w nich zawartych oraz zastępują wszelkie inne porozumienia, uzgodnienia i umowy dotyczące przedmiotu (treści) niniejszych Og&oacute;lnych warunk&oacute;w.</span></p>
        <p style="text-align: center;"><span style="font-size: 20px; color: rgb(255, 255, 255);"><strong>XI. ZMIANA WARUNK&Oacute;W STRONY INTERNETOWEJ</strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Właściciel strony internetowej zastrzega sobie prawo do dokonywania modyfikacji niniejszych Og&oacute;lnych warunk&oacute;w, w dowolnym momencie ich obowiązywania, zamieszczając ich zaktualizowaną wersję na stronie internetowej, kt&oacute;re zaczynają obowiązywać Użytkownik&oacute;w od momentu ich publikacji, chyba że inaczej wskazano w zmodyfikowanych Og&oacute;lnych warunkach.</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Użytkownik ma obowiązek zapoznania się z modyfikacjami Og&oacute;lnych warunk&oacute;w, o czym Właściciel poinformuje go, wysyłając do Niego wiadomość lub komunikat o zmianach Og&oacute;lnych warunk&oacute;w do zaakceptowania.</span></p>
        <p><span style="color: rgb(255, 255, 255);">3. Dalsze korzystanie ze strony internetowej jest r&oacute;wnoznaczne z akceptacją zmodyfikowanych Warunk&oacute;w strony internetowej.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">XII. ROZWIĄZYWANIE SPOR&Oacute;W</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. Wszelkie powstałe spory Strony postanawiają w pierwszej kolejności rozwiązać w trybie polubownego załatwienia sprawy, przed właściwym sądem polubownym (zapis na sąd polubowny).</span></p>
        <p><span style="color: rgb(255, 255, 255);">2. Jeśli polubowne załatwienie sprawy okaże się niemożliwe, sp&oacute;r wynikający z niniejszej umowy zostanie rozstrzygnięty przez sąd, w kt&oacute;rego okręgu znajduje się siedziba Właściciela.</span></p>
        <p style="text-align: center;"><span style="color: rgb(255, 255, 255);"><strong><span style="font-size: 20px;">XIII. PODSTAWA PRAWNA</span></strong></span></p>
        <p><span style="color: rgb(255, 255, 255);">1. W sprawach nieuregulowanych w niniejszych Og&oacute;lnych warunkach stosuje się odpowiednio następujące ustawy:</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">a. ustawę prawo telekomunikacyjne z dnia 16 lipca 2004 r. (tj. Dz.U. z 2019 r. poz. 2460, ze zm.);</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">b. ustawę o świadczeniu usług drogą elektroniczną z dnia 18 lipca 2002 r. (t.j. Dz.U. z 2019 r. poz. 123, ze zm.);</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">c. ustawę o prawie autorskim i prawach pokrewnych z dnia 4 lutego 1994 r. (t.j. Dz.U. z 2019 r. poz. 1231, ze zm.);</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">d. ustawę Kodeks Cywilny z dnia 23 kwietnia 1964 r. (t.j. Dz.U. z 2019 r. poz. 1145, ze zm.);</span></p>
        <p style="margin-left: 20px;"><span style="color: rgb(255, 255, 255);">oraz inne właściwe przepisy prawa polskiego.</span></p>
        <p><span style="color: rgb(255, 255, 255);"><br></span></p>
        <p><br></p>
    </div>
    <a href="{{ route('register') }}" class="btn btn-warning btn-block">Wróć</a>
</div>
@endsection